### ISSUE TITLE
Possible modifications to message methods

### ISSUE THREAD

**Issue by kromg** [monitoring-plugins/monitoring-plugin-perl#14]
Hi, 
    since message methods are marked as experimental in Monitoring::Plugin documentation, I made my own methods for a plugin I wrote some time ago (not wanting to depend on something which may change without notice). Since I need them now for another plugin, I'm facing the problem of sharing that code between the two scripts, trying to keep around as less extra modules as possible. 

Ideally, the best solution would be to integrate those methods into Monitoring::Plugin distribution (if you like the way they work). Is this a possibility we can discuss?

 You can find the code I made into: https://github.com/kromg/nagios-plugins/blob/master/check_end2end.pl, it's the Monitoring::Plugin::Ens2End package. The package can also keep track of the current status of the check, it's made to handle those checks where the overall exit status is built from many sub-checks. 

Thanks, 
Giacomo

**Comment by sni** [comment]
I'd say we can remove the "experimental" tag there. It had been there for years now and i see no reason why we would change them.

**Comment by tejr** [comment]
I use these methods extensively and would really like to see them labelled as stable. Stacking up messages during a run and raising the status of the most severe problem, if any, with a concatenation of all the messages, is something I seem to have to do in at least half of all the plugins I write.

Please excuse the issue necromancy...

**Comment by sni** [comment]
Pull requests are welcome.
