### ISSUE TITLE
Can't locate Monitoring/Plugin.pm

### ISSUE THREAD

**Issue by sirio81** [monitoring-plugins/monitoring-plugin-perl#6]
Problem: when rinning 'bin/check_raid.pl -S' I get this error

<pre>
Can't locate Monitoring/Plugin.pm in @INC (you may need to install the Monitoring::Plugin module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at bin/check_raid.pl line 2.
BEGIN failed--compilation aborted at bin/check_raid.pl line 2.
</pre>

Environment: debian 8.2 x86_64 and debian 7.8 x86_64.

Steps:
downloaded the plugin in /tmp and extracted the tar.gz.
cd nagios-plugin-check_raid-master

Following the readme I run bin/check_raid.pl -S but I get the errore above.
I also tried to install libnagios-object-perl and libnagios-plugin-perl as suggested in this post
http://www.monitoring-portal.org/wbb/index.php?page=Thread&threadID=25251

In this other post they point out the issue about a path:
https://viewsby.wordpress.com/2014/02/20/perlnagios-cant-locate-utils-pm-in-inc/

I hope I'm not missing something trivial.

**Comment by waja** [comment]
This seems not to be an issue with Monitoring::Plugin but with your plugin you are using. You might need to install the [libmonitoring-plugin-perl](https://packages.debian.org/search?keywords=libmonitoring-plugin-perl) Debian package or install it like described in the [README](https://github.com/monitoring-plugins/monitoring-plugin-perl/blob/master/README).

**Comment by waja** [comment]
Anyway ... I've uploaded libmonitoring-plugin-perl into jessie-backports but that might sit in the [NEW queue](https://ftp-master.debian.org/backports-new.html). In the meanwhile you can grab the package from my repository. See http://ftp.cyconet.org/instructions for instruction how to do that.

**Comment by C0rn3j** [comment]
Looks like the dep is `libmonitoring-plugin-perl` on Ubuntu 18.04 too nowadays.

Can't this be just closed?

**Comment by sni** [comment]
that's right, closing this one... thanks for noticing
